version: '3.4'
services:
  mongo:
    image: mongo
    hostname: mongodb
    ports:
      - '27017:27017'
    command: ['--replSet', 'rs0', '--bind_ip_all']
  api:
    build: packages/api
    command: npm start
    network_mode: host
    ports:
      - '3001:3001'
    volumes:
      - tradulab:/var/lib/files
  process-input-file:
    build: packages/process-input-file
    command: npm start
    volumes:
      - tradulab:/var/lib/files
  web:
    build: packages/web
    command: npm start
    ports:
      - '3000:3000'
    network_mode: host
    depends_on:
      - api
volumes:
  tradulab:
