version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
<<<<<<< HEAD
  api:
    build: packages/api
    command: npm start
    network_mode: host
    ports:
      - "3001:3001"
    volumes:
      - tradulab:/var/lib/files
  web:
    build: packages/web
    command: npm start
    ports:
      - "3000:3000"
    network_mode: host
    depends_on:
      - api
volumes:
  tradulab:
=======
volumes:
  db-data:
>>>>>>> bolivar
