version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - tradulab:/var/lib/db
  api:
    build: packages/api
    command: npm start
    ports:
      - "3001:3001"
  web:
    build: packages/web
    command: npm start
    ports:
      - "3000:3000"
    network_mode: host
    depends_on:
      - api
volumes:
  tradulab:
