version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  api:
    build: packages/api
    command: npm start
    network_mode: host
    ports:
      - "3001:3001"
    volumes:
      - tradulab:/var/lib/files
=======
  api:
    build: packages/api
    command: npm start
    ports:
      - "3001:3001"
>>>>>>> Create API and WEB Images
  web:
    build: packages/web
    command: npm start
    ports:
      - "3000:3000"
<<<<<<< HEAD
    network_mode: host
    depends_on:
      - api
volumes:
  tradulab:
=======
volumes:
  db-data:
>>>>>>> bolivar
=======
    depends_on:
      - api
>>>>>>> Create API and WEB Images
=======
>>>>>>> revert docker compose port
