version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build: packages/api
    command: npm start
<<<<<<< HEAD
    network_mode: host
=======
>>>>>>> 418d06821d80122b185dd9ddfeffe20d0159bf82
    ports:
      - "3001:3001"
    volumes:
      - tradulab:/var/lib/files
  web:
    build: packages/web
    command: npm start
    ports:
      - "3000:3000"
    network_mode: host
    depends_on:
      - api
volumes:
  tradulab:
