version: '3.4'
services:
  mongo:
    image: mongo
    command: ['--replSet', 'rs0', '--bind_ip_all']
  api:
    build: packages/api
    command: npm run dev
    environment:
      MONGO_CONNECTION_URI: mongodb://mongo/tradulab
      JWT_SECRET: morango
      EXPRESS_PORT: 3001
    ports:
      - '3001:3001'
    volumes:
      - ./packages/api/src/:/usr/src/tradulab/api/src
      - tradulab:/var/lib/files
    links:
      - mongo
  process-input-file:
    build: packages/process-input-file
    command: npm start
    volumes:
      - tradulab:/var/lib/files
  web:
    build: packages/web
    command: npm start
    ports:
      - '3000:3000'
    network_mode: host
    depends_on:
      - api
volumes:
  tradulab:
